"""auto

Revision ID: 14a04daeb2f9
Revises: 48ecb1e0a38a
Create Date: 2025-11-29 22:29:25.234048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a04daeb2f9'
down_revision: Union[str, Sequence[str], None] = '48ecb1e0a38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scustom', sa.Column('phone_number', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scustom', 'phone_number')
    # ### end Alembic commands ###
