"""auto

Revision ID: 48ecb1e0a38a
Revises: af2a0df5df44
Create Date: 2025-11-29 21:30:54.722030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ecb1e0a38a'
down_revision: Union[str, Sequence[str], None] = 'af2a0df5df44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbook', sa.Column('seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbook', 'seats')
    # ### end Alembic commands ###
