"""create initial tables

Revision ID: aa62f5029ddc
Revises: 
Create Date: 2025-11-29 01:44:19.560368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa62f5029ddc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sairport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scarr',
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('carrname', sa.String(length=50), nullable=False),
    sa.Column('carrcode', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('carrid'),
    sa.UniqueConstraint('carrid')
    )
    op.create_table('scustom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('spfli',
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('connid', sa.Integer(), nullable=False),
    sa.Column('airpfrom', sa.Integer(), nullable=False),
    sa.Column('airpto', sa.Integer(), nullable=False),
    sa.Column('fltime', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airpfrom'], ['sairport.id'], ),
    sa.ForeignKeyConstraint(['airpto'], ['sairport.id'], ),
    sa.ForeignKeyConstraint(['carrid'], ['scarr.carrid'], ),
    sa.PrimaryKeyConstraint('carrid', 'connid')
    )
    op.create_table('sflight',
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('connid', sa.Integer(), nullable=False),
    sa.Column('fldate', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('planetype', sa.String(length=30), nullable=False),
    sa.Column('seatsmax', sa.Integer(), nullable=False),
    sa.Column('seatsocc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrid', 'connid'], ['spfli.carrid', 'spfli.connid'], ),
    sa.ForeignKeyConstraint(['carrid'], ['scarr.carrid'], ),
    sa.PrimaryKeyConstraint('carrid', 'connid', 'fldate')
    )
    op.create_table('sbook',
    sa.Column('carrid', sa.Integer(), nullable=False),
    sa.Column('connid', sa.Integer(), nullable=False),
    sa.Column('fldate', sa.Date(), nullable=False),
    sa.Column('bookid', sa.Integer(), nullable=False),
    sa.Column('customid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrid', 'connid', 'fldate'], ['sflight.carrid', 'sflight.connid', 'sflight.fldate'], ),
    sa.ForeignKeyConstraint(['carrid'], ['scarr.carrid'], ),
    sa.ForeignKeyConstraint(['customid'], ['scustom.id'], ),
    sa.PrimaryKeyConstraint('carrid', 'connid', 'fldate', 'bookid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sbook')
    op.drop_table('sflight')
    op.drop_table('spfli')
    op.drop_table('scustom')
    op.drop_table('scarr')
    op.drop_table('sairport')
    # ### end Alembic commands ###
